version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: zaitoon_erp
      POSTGRES_USER: erpuser
      POSTGRES_PASSWORD: erppass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: zaitoon_erp
      DB_USER: erpuser
      DB_PASSWORD: erppass
      JWT_SECRET: changeme
      JWT_EXPIRES: 30d
      ADMIN_EMAIL: admin@zaitoon.store
      ADMIN_PASSWORD: admin123
    depends_on:
      - db
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:80"
volumes:
  dbdata:
